
# SUM OF TWO VECTORS

In [4]:
%%file 1_a.py
from mpi4py import MPI
import numpy as np
import random
import time
comm=MPI.COMM_WORLD
rank=comm.Get_rank()
size=comm.Get_size()
workers= size-1
Answer = []
    


vector_size=10**2
np.random.seed(seed=1)
M1=np.random.randint(9,size=vector_size)  
M2=np.random.randint(9,size=vector_size)

print("\nVector 1 is",M1)
print("and Vector2 is",M2)

print("Size",size)
if rank==0:
    print(rank,"is MASTER")
    Start=MPI.Wtime()          

    Vector_1=np.array_split(M1,workers)        

    Vector_2=np.array_split(M2,workers)


    

    for i in range(1,size):

        comm.send(Vector_1[i-1],dest=i)
        comm.send(Vector_2[i-1],dest=i)
  
   
    for i in range(1,size):
        X=comm.recv(source=i)
        Answer=np.concatenate((Answer, X), axis=None)
        
    print("Final Vector Sum is",Answer)
    
    End=MPI.Wtime()
    print("Total time taken",(End-Start))



else:
    print(rank,"is WORKER")
    A=comm.recv(source=0)
    B=comm.recv(source=0)

    print("Data received in process",rank,"are",A,B)
    C=[]
    for i in range(len(A)):
        C.append(A[i]+B[i])

    comm.send(C,dest=0)
    print("Data sent from",rank ,"is", C)
    
            
print(MPI.Wtime())



Overwriting 1_a.py


In [5]:
!mpiexec -n 2 python 1_a.py


Vector 1 is [5 8 5 0 0 1 7 6 2 4 5 2 4 2 4 7 7 1 7 0 6 7 6 1 0 1 8 8 3 8 7 3 6 5 1 3 4
 8 1 4 0 3 2 0 4 2 7 7 8 6 3 7 7 4 5 3 6 8 0 2 7 7 7 3 0 8 7 7 1 1 3 0 8 6
 4 5 6 2 5 7 8 4 4 7 7 4 0 2 0 7 1 7 8 4 0 1 8 2 3 1]
and Vector2 is [2 7 2 6 0 2 6 6 2 7 7 0 6 5 1 4 6 0 6 5 1 2 1 5 4 0 7 8 5 7 0 3 1 4 4 6 8
 8 2 7 5 5 4 5 8 5 8 1 1 8 7 0 3 4 2 0 3 5 1 2 4 3 0 6 0 7 2 8 3 0 8 4 2 0
 3 8 1 4 3 3 6 7 3 5 3 2 4 4 0 3 3 8 3 5 6 7 5 1 7 0]
Size 2
1 is WORKER
Data received in process 1 are [5 8 5 0 0 1 7 6 2 4 5 2 4 2 4 7 7 1 7 0 6 7 6 1 0 1 8 8 3 8 7 3 6 5 1 3 4
 8 1 4 0 3 2 0 4 2 7 7 8 6 3 7 7 4 5 3 6 8 0 2 7 7 7 3 0 8 7 7 1 1 3 0 8 6
 4 5 6 2 5 7 8 4 4 7 7 4 0 2 0 7 1 7 8 4 0 1 8 2 3 1] [2 7 2 6 0 2 6 6 2 7 7 0 6 5 1 4 6 0 6 5 1 2 1 5 4 0 7 8 5 7 0 3 1 4 4 6 8
 8 2 7 5 5 4 5 8 5 8 1 1 8 7 0 3 4 2 0 3 5 1 2 4 3 0 6 0 7 2 8 3 0 8 4 2 0
 3 8 1 4 3 3 6 7 3 5 3 2 4 4 0 3 3 8 3 5 6 7 5 1 7 0]
Data sent from 1 is [7, 15, 7, 6, 0, 3, 13, 12, 4, 11, 12, 2, 10, 7, 5, 11, 13, 1, 13, 5, 7, 9, 7, 6, 4, 1

---


# AVERAGE OF A VECTOR

In [6]:
%%file 1_b.py
from mpi4py import MPI
import numpy as np
import time
comm=MPI.COMM_WORLD
rank=comm.Get_rank()
size=comm.Get_size()
Workers= size-1
Answer = []
    


Vector_size=10**2
np.random.seed(seed=1000)
V_1=np.random.randint(9,size=Vector_size) 
print("\nRandom Vector generated is",V_1)
print("size",size)
if rank==0:
    print(rank,"is MASTER")
    Start=MPI.Wtime()
    Vector=np.array_split(V_1,Workers)  
    for i in range(1,size):

        comm.send(Vector[i-1],dest=i)
    
   
    for i in range(1,size):
        X=comm.recv(source=i)
        Answer=np.append(Answer, X)
        
    
    print("Total average is",np.mean(Answer))
    End=MPI.Wtime()
    print("Total time taken",(End-Start))



else:
    print(rank,"is WORKER")
    A=comm.recv(source=0)
    print("Data received in",rank,"is",A)
    B=np.mean(A)
  

    comm.send(B,dest=0)
    print("Avg value sent from",rank ,"is", B)
    


            
print(MPI.Wtime())





Overwriting 1_b.py


In [7]:
!mpiexec -n 8 python 1_b.py


Random Vector generated is [3 7 7 0 1 0 8 4 4 4 2 8 2 4 2 5 5 4 0 4 2 5 4 7 0 4 7 1 0 2 1 7 1 5 6 5 7
 8 8 2 2 6 3 3 6 5 8 4 1 0 1 8 8 0 2 3 6 2 5 8 5 6 6 7 6 3 4 8 1 3 7 2 0 4
 4 1 6 5 1 4 1 7 4 5 0 6 2 7 0 8 0 5 3 0 4 3 3 3 6 4]
size 8
3 is WORKER
Data received in 3 is [1 7 1 5 6 5 7 8 8 2 2 6 3 3]
Avg value sent from 3 is 4.571428571428571
1621411.6513008408

Random Vector generated is [3 7 7 0 1 0 8 4 4 4 2 8 2 4 2 5 5 4 0 4 2 5 4 7 0 4 7 1 0 2 1 7 1 5 6 5 7
 8 8 2 2 6 3 3 6 5 8 4 1 0 1 8 8 0 2 3 6 2 5 8 5 6 6 7 6 3 4 8 1 3 7 2 0 4
 4 1 6 5 1 4 1 7 4 5 0 6 2 7 0 8 0 5 3 0 4 3 3 3 6 4]
size 8
2 is WORKER
Data received in 2 is [5 5 4 0 4 2 5 4 7 0 4 7 1 0 2]
Avg value sent from 2 is 3.3333333333333335
1621411.6574131884

Random Vector generated is [3 7 7 0 1 0 8 4 4 4 2 8 2 4 2 5 5 4 0 4 2 5 4 7 0 4 7 1 0 2 1 7 1 5 6 5 7
 8 8 2 2 6 3 3 6 5 8 4 1 0 1 8 8 0 2 3 6 2 5 8 5 6 6 7 6 3 4 8 1 3 7 2 0 4
 4 1 6 5 1 4 1 7 4 5 0 6 2 7 0 8 0 5 3 0 4 3 3 3 6 4]
size 8
4 is WORKER
Data received in

---


# VECTOR-MATRIX MULTIPLICATION

In [8]:
%%file ex2.py
from mpi4py import MPI
import numpy as np
import time
comm=MPI.COMM_WORLD
rank=comm.Get_rank()
size=comm.Get_size()
workers= size-1
Answer=[]


vector_size=10**2
print("\nSize",size)
if rank==0:
    print(rank,"is MASTER")
    Start=MPI.Wtime()        
    v1=np.random.randint(10,size=(1,vector_size))
    v2=np.random.randint(10,size=(vector_size,vector_size))
 
    print("The vectors considered for multiplication are M1:",v1)
    print("and M2",v2)
    M2=np.array_split(v2,workers,axis=1)
        

    for i in range(1,size):

        comm.send(v1,dest=i)
        comm.send(M2[i-1],dest=i)

       
   
   
    for i in range(1,size):
        Z=comm.recv(source=i)
        Answer=np.concatenate((Answer, Z), axis=None)
        
    print("Final Answer is ",Answer)   
    
    
    End=MPI.Wtime()
    print("Total time taken",(End-Start))
        
    
  




else:
    print(rank,"is WORKER")
    A=comm.recv(source=0)
    B=comm.recv(source=0)

    print("Data received in process number",rank, "are:", A,"\n","and",B)
    X=[]
    X.append(np.dot(A,B))

    comm.send(X,dest=0)
    print("Data sent from",rank ,"is", X)
    

print(MPI.Wtime())


Overwriting ex2.py


In [9]:
!mpiexec -n 8 python ex2.py


Size 8
1 is WORKER
Data received in process number 1 are: [[0 8 0 4 7 8 7 1 4 2 0 7 8 2 5 8 6 4 9 0 5 6 4 8 8 7 2 0 3 2 7 7 8 2 3 5
  0 4 9 1 2 1 9 1 9 4 2 2 2 4 9 7 0 3 3 7 6 4 8 1 8 7 6 4 9 1 7 9 5 8 3 3
  2 9 5 6 4 8 3 0 2 5 6 8 1 1 3 5 5 3 8 5 9 3 1 3 1 8 3 5]] 
 and [[1 5 9 ... 1 5 9]
 [5 1 0 ... 9 4 9]
 [7 0 1 ... 5 8 0]
 ...
 [9 9 2 ... 4 6 0]
 [4 1 5 ... 5 8 1]
 [4 2 4 ... 2 5 8]]
Data sent from 1 is [array([[1914, 1926, 1783, 2190, 1844, 1968, 1957, 2022, 2051, 1895, 1929,
        2141, 1940, 2108, 1789]])]
1621448.9766276833

Size 8
2 is WORKER
Data received in process number 2 are: [[0 8 0 4 7 8 7 1 4 2 0 7 8 2 5 8 6 4 9 0 5 6 4 8 8 7 2 0 3 2 7 7 8 2 3 5
  0 4 9 1 2 1 9 1 9 4 2 2 2 4 9 7 0 3 3 7 6 4 8 1 8 7 6 4 9 1 7 9 5 8 3 3
  2 9 5 6 4 8 3 0 2 5 6 8 1 1 3 5 5 3 8 5 9 3 1 3 1 8 3 5]] 
 and [[1 9 7 ... 3 3 1]
 [6 9 8 ... 2 8 4]
 [3 5 7 ... 5 4 8]
 ...
 [5 1 4 ... 4 6 0]
 [0 0 2 ... 8 5 4]
 [5 6 4 ... 5 1 2]]
Data sent from 2 is [array([[2193, 2082, 1977, 2249, 1955, 1744, 

---


# MATRIX-MATRIX MULTIPLICATION

In [10]:
%%file exercise3.py
from mpi4py import MPI
import numpy as np
import time
comm=MPI.COMM_WORLD
rank=comm.Get_rank()
size=comm.Get_size()
Size = comm.Get_size()
print("Number of processes are :", Size)

print(rank,size)
Matrix_size=10
if rank==0:

    M1=np.random.randint(9,size=(Matrix_size,Matrix_size))
    M2=np.random.randint(9,size=(Matrix_size,Matrix_size))
    Start=MPI.Wtime()
    PRODUCT=np.random.randint(9,size=(Matrix_size,Matrix_size))

ROWS=[]
COLS=[]
for row in range(Matrix_size):

    for col in range(Matrix_size):

        if rank==0:
            ROWS=np.array_split(M1[row,:],size)     
            COLS=np.array_split(M2[:,[col]],size)  

        row_scatter=comm.scatter(ROWS,0)           
        col_scatter=comm.scatter(COLS,0)

        Dot = np.dot(row_scatter, col_scatter)
        Gathered = comm.gather(Dot, 0)    

        if rank == 0:
            PRODUCT[row][col] = np.sum(Gathered)


if rank == 0:
    print("Matrix 1:",M1)
    print("Matrix 2:",M2)
    print("Dot Product is:",PRODUCT)
    End = MPI.Wtime()
    Time_diff = End - Start
    print("Time taken = \n" ,Time_diff)


Overwriting exercise3.py


In [11]:
!mpiexec -n 2 python exercise3.py

Number of processes are : 2
1 2
Number of processes are : 2
0 2
Matrix 1: [[1 0 6 3 0 0 6 5 8 8]
 [3 0 5 8 7 2 1 5 5 5]
 [0 1 0 6 4 7 5 6 1 8]
 [0 4 4 7 3 2 6 4 0 8]
 [4 1 6 3 7 4 0 7 2 2]
 [1 8 5 8 8 7 5 2 8 1]
 [1 4 5 6 2 1 5 7 2 1]
 [1 5 0 7 8 0 7 3 5 8]
 [1 6 8 6 0 0 6 0 7 3]
 [4 0 0 4 4 1 6 7 1 8]]
Matrix 2: [[6 5 6 8 6 1 8 5 3 3]
 [3 6 1 7 5 6 6 0 8 1]
 [1 1 6 5 4 2 5 7 5 2]
 [1 2 7 1 0 6 2 7 2 8]
 [5 2 3 8 4 6 6 7 4 6]
 [8 5 5 2 7 7 3 5 7 0]
 [8 0 5 6 2 2 4 8 4 7]
 [8 4 3 3 4 5 7 5 3 7]
 [0 7 0 7 6 7 5 4 2 1]
 [7 3 2 4 3 5 8 8 5 5]]
Dot Product is: [[159 117 124 180 134 164 207 237 134 164]
 [165 130 165 193 147 204 217 258 146 197]
 [229 116 149 146 134 202 194 243 165 191]
 [190  98 154 163 114 178 198 240 168 196]
 [173 120 148 179 155 169 203 211 147 152]
 [202 192 192 271 216 285 248 277 236 195]
 [150 100 141 154 114 154 171 192 137 168]
 [204 136 144 232 143 225 238 265 176 227]
 [107 119 138 193 131 165 179 203 156 137]
 [216 100 136 166 117 153 209 232 130 200]]
Time ta